services:
  nginx-proxy:
    build: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment: 
      - FLASK_SERVER_ADDR=flask-app:5000
    ports:
      - "80:80"
    depends_on:
      - flask-app
  flask-app:
    build: flask
    restart: always
    depends_on:
      - redis
  redis:
    image: redis    